episode-length: 20
perma-day : true
perma-day-ep : 3
should-shrink : true
shrink-size : 100
shrink-ep : 3
shrink-time : 60

UHCWorld : world
hubWorld : hub

hubCentreX : 0
hubCentreY : 0
hubCentreZ : 0

teams : true
moles: false

season13 : false
season14 : false
season14-radius : 25
team-size : 2
table-name : Season14

apple-rate : 1
pearl-rate : 100
death-lighting : false
fall-damage : true
pearl-damage : true

can-spectate : true