name: KoOUHC
main: me.JoeShuff.KoO.KoOUHC
version: 1.0
commands:
   teams:
      description: Randomly Select Teams.
      usage: /<command>
   clearteams:
      description: Removes all teams created by this plugin.
      usage: /<command>
   prepuhc:
      description: Prepare the world for a UHC.
      usage: /<command>
   showkills:
      description: Add the kill count to the sidebar.
      usage: /<command>
   pvp:
      description: Toggle PVP for the world.
      usage: /<command>
   loc:
      description: Gen locations and TP players.
      usage: /<command>
   team:
      description: Chosen team with people.
      usage: /<command>
   start-uhc:
      description: Start the UHC.
      usage: /<command>
   tchat:
      description: Chat with your teammates
      usage: /<command>
   tloc:
      description: Send your location to teammates.
      usage: /<command>
   tl:
      description: Send your location to teammates.
      usage: /<command>
   edituhc:
      description: Edit UHC rules.
      usage: /<command>
   rules:
      description: View UHC rules.
      usage: /<command>
   worldtest:
      description: Test to see if the worlds exist.
      usage: /<command>
   stop-uhc:
      description: Stop the UHC.
      usage: /<command>
   teamname:
      description: Stop the UHC.
      usage: /<command>